### ISSUE TITLE
How to solve this ?

### ISSUE THREAD

**Issue by Floopy1720** [discretegames/PythonPrison#1]
Traceback (most recent call last):
  File "run_game.py", line 2, in <module>
    import code.game
  File "/home/floopy1703/PythonPrison/code/game.py", line 6, in <module>
    from code.level import Level
  File "/home/floopy1703/PythonPrison/code/level.py", line 7, in <module>
    from code.region import Region
  File "/home/floopy1703/PythonPrison/code/region.py", line 39
    return *self.start, *self.end
           ^
SyntaxError: invalid syntax

**Comment by discretegames** [comment]
You might be trying to run the game in Python 2 where that type of syntax didn't exist. Make sure you're using Python 3.8.5 or later to play Python Prison.

**Comment by Floopy1720** [comment]
Does it work on python 3.7.3

**Comment by discretegames** [comment]
I never tested it in Python 3.7.3 but there's a decent chance it will work fine.
